%% ========================================================================
%% CHANGED FUNCTIONS — paste these over the matching functions in your script
%% (keep apEpoxyLabel at the bottom of the script; it is not repeated here)
%%
%% Changes are marked with:   % <<< CHANGED
%% ========================================================================


%% ========================================================================
%% Plot average curves for 2023, 2024, 2025, and 2026
%%
%% New behavior
%%   - Title is just "Material Test"  (e.g. NEAT Compression, CNT Tension)
%%   - Legend entries use AP/Epoxy ratios instead of years
%%   - X and Y axis labels are bold, size 20
%%   - drawFailureLine = true adds, for Tension and Fracture only:
%%         * a vertical drop line at the mean fracture point
%%         * a horizontal standard-deviation band of the fracture x-locations
%%   - Compression is never given a failure line
%% ========================================================================

function plotYearlyAverageCurvesv3( ...
    classifiedAll, organizedFolder, materials, tests, ...
    plotLimits, outputFolder, drawFailureLine)

    if nargin < 7 || isempty(drawFailureLine)
        drawFailureLine = false;
    end

    yearsToPlot = ["2023","2024","2025","2026"];

    % Number of interpolation points used for every average curve
    numberOfAveragePoints = 500;

    %% One color for each year
    yearColors = lines(length(yearsToPlot));

    for t = 1:length(tests)

        testName = string(tests{t});

        % The failure line only applies to Tension and Fracture
        addLineForThisTest = drawFailureLine && ...
            ( strcmpi(testName,'Tension') || strcmpi(testName,'Fracture') );

        for m = 1:length(materials)

            materialName = string(materials{m});

            fig = figure( ...
                'Visible','on', ...
                'Units','normalized', ...
                'Position',[0.10 0.10 0.75 0.75]);

            ax = axes(fig);

            hold(ax,'on');
            grid(ax,'on');
            box(ax,'on');

            plottedYears = strings(0);
            plotHandles = gobjects(0);

            for y = 1:length(yearsToPlot)

                yearNumber = yearsToPlot(y);
                yearFolderName = yearNumber + "_organized";

                %% Select this year, material, and test
                rows = ...
                    strcmpi(string(classifiedAll.Year), ...
                            yearFolderName) & ...
                    strcmpi(string(classifiedAll.Test), ...
                            testName) & ...
                    strcmpi(string(classifiedAll.Material), ...
                            materialName);

                selected = classifiedAll(rows,:);

                fprintf( ...
                    '\nAverage processing: %s %s %s — %d files\n', ...
                    yearNumber, ...
                    materialName, ...
                    testName, ...
                    height(selected));

                if isempty(selected)
                    warning( ...
                        'No files found for %s %s %s.', ...
                        yearNumber, materialName, testName);
                    continue;
                end

                %% Read the dimension file for this year
                dims = table();

                if ~strcmpi(testName,'Fracture')

                    dimensionFile = fullfile( ...
                        organizedFolder, ...
                        yearFolderName, ...
                        "SpecimenDimensions" + yearNumber + ".xlsx");

                    if ~isfile(dimensionFile)
                        warning( ...
                            'Dimension file not found: %s', ...
                            dimensionFile);
                        continue;
                    end

                    dims = readtable(dimensionFile);

                    if ~ismember( ...
                            'Material', ...
                            dims.Properties.VariableNames)

                        dims.Properties.VariableNames{2} = ...
                            'Material';
                    end
                end

                %% Store every successfully processed curve
                xCurves = cell(0);
                yCurves = cell(0);

                for i = 1:height(selected)

                    csvPath = string(selected.FilePath(i));

                    if ~isfile(csvPath)
                        warning('CSV not found: %s', csvPath);
                        continue;
                    end

                    groupName = string(selected.Group(i));

                    sectionNumber = str2double( ...
                        regexprep(groupName,'\D',''));

                    sampleName = string(selected.SampleName(i));

                    sampleNumber = str2double( ...
                        regexprep(sampleName,'\D',''));

                    [xCurve, yCurve, ok] = ...
                        processCurveForYearlyAverage( ...
                            csvPath, ...
                            dims, ...
                            sectionNumber, ...
                            sampleNumber, ...
                            testName, ...
                            materialName, ...
                            plotLimits);

                    if ~ok
                        continue;
                    end

                    xCurves{end+1,1} = xCurve;
                    yCurves{end+1,1} = yCurve;
                end

                if isempty(xCurves)
                    warning( ...
                        'No valid curves for %s %s %s.', ...
                        yearNumber, materialName, testName);
                    continue;
                end

                %% Find range shared by all curves
                curveStarts = cellfun(@(x) min(x), xCurves);
                curveEnds = cellfun(@(x) max(x), xCurves);

                commonStart = max(curveStarts);
                commonEnd = min(curveEnds);

                if commonEnd <= commonStart
                    warning( ...
                        ['The curves do not have a common x range for ' ...
                         '%s %s %s.'], ...
                        yearNumber, materialName, testName);
                    continue;
                end

                %% Common x-axis for interpolation
                commonX = linspace( ...
                    commonStart, ...
                    commonEnd, ...
                    numberOfAveragePoints)';

                interpolatedY = NaN( ...
                    numberOfAveragePoints, ...
                    length(xCurves));

                %% Interpolate every specimen onto commonX
                for c = 1:length(xCurves)

                    xCurrent = xCurves{c};
                    yCurrent = yCurves{c};

                    [xCurrent, uniqueIndices] = ...
                        unique(xCurrent,'stable');

                    yCurrent = yCurrent(uniqueIndices);

                    if length(xCurrent) < 2
                        continue;
                    end

                    interpolatedY(:,c) = interp1( ...
                        xCurrent, ...
                        yCurrent, ...
                        commonX, ...
                        'linear', ...
                        NaN);
                end

                %% Remove failed interpolation columns
                validColumns = ...
                    sum(isfinite(interpolatedY),1) >= 2;

                interpolatedY = ...
                    interpolatedY(:,validColumns);

                if isempty(interpolatedY)
                    warning( ...
                        'Interpolation failed for %s %s %s.', ...
                        yearNumber, materialName, testName);
                    continue;
                end

                %% Fracture point of each contributing specimen (Tension and
                %% Fracture only), taken as each specimen's maximum y value.
                fractureXValues = [];
                fractureYValues = [];

                if addLineForThisTest

                    validXCurves = xCurves(validColumns);
                    validYCurves = yCurves(validColumns);

                    fractureXValues = nan(numel(validXCurves),1);
                    fractureYValues = nan(numel(validXCurves),1);

                    for c = 1:numel(validXCurves)

                        xc = validXCurves{c};
                        yc = validYCurves{c};

                        [peakY, peakIdx] = max(yc);

                        if isfinite(peakY)
                            fractureXValues(c) = xc(peakIdx);
                            fractureYValues(c) = peakY;
                        end
                    end
                end

                %% Number of specimens contributing at each x-value
                contributingCount = sum(isfinite(interpolatedY),2);

                %% Point-by-point average
                averageY = mean( ...
                    interpolatedY, ...
                    2, ...
                    'omitnan');

                %% Point-by-point sample standard deviation
                standardDeviationY = std( ...
                    interpolatedY, ...
                    0, ...
                    2, ...
                    'omitnan');

                %% Standard deviation requires at least two specimens
                standardDeviationY(contributingCount < 2) = NaN;

                %% Cut the final fracture average at maximum force
                if strcmpi(testName,'Fracture')

                    [~, averagePeakIndex] = max(averageY);

                    commonX = commonX(1:averagePeakIndex);
                    averageY = averageY(1:averagePeakIndex);
                    standardDeviationY = ...
                        standardDeviationY(1:averagePeakIndex);
                end

                %% Calculate standard-deviation limits
                lowerBound = averageY - standardDeviationY;
                upperBound = averageY + standardDeviationY;

                %% Prevent negative force or stress in shaded region
                lowerBound(lowerBound < 0) = 0;

                %% Select this year's color
                thisColor = yearColors(y,:);

                %% Only shade locations with a valid standard deviation
                validShade = ...
                    isfinite(commonX) & ...
                    isfinite(lowerBound) & ...
                    isfinite(upperBound);

                xShade = commonX(validShade);
                lowerShade = lowerBound(validShade);
                upperShade = upperBound(validShade);

                %% Draw standard-deviation region first
                if length(xShade) >= 2

                    fill( ...
                        ax, ...
                        [xShade; flipud(xShade)], ...
                        [lowerShade; flipud(upperShade)], ...
                        thisColor, ...
                        'FaceAlpha',0.16, ...
                        'EdgeColor','none', ...
                        'HandleVisibility','off');
                end

                %% Draw yearly average over the shaded region
                h = plot( ...
                    ax, ...
                    commonX, ...
                    averageY, ...
                    'Color',thisColor, ...
                    'LineWidth',2.5);

                plotHandles(end+1) = h;

                plottedYears(end+1) = ...
                    apEpoxyLabel(yearNumber) + ...          % <<< CHANGED
                    " mean \pm SD (n = " + ...
                    string(size(interpolatedY,2)) + ")";

                %% ============================================================
                %% Fracture points + mean drop line + spread band
                %% (Tension and Fracture only)
                %% ============================================================
                if addLineForThisTest

                    finiteMask = ...
                        isfinite(fractureXValues) & isfinite(fractureYValues);

                    fractureX = fractureXValues(finiteMask);
                    fractureY = fractureYValues(finiteMask);

                    if ~isempty(fractureX)

                        meanFractureX = mean(fractureX);
                        meanFractureY = mean(fractureY);

                        if numel(fractureX) >= 2
                            stdFractureX = std(fractureX,0);
                        else
                            stdFractureX = 0;
                        end

                        fprintf( ...
                            ['%s %s %s: fracture (max-y) points = %d, ' ...
                             'mean fracture x = %.4g, std = %.4g\n'], ...
                            yearNumber, materialName, testName, ...
                            numel(fractureX), meanFractureX, stdFractureX);

                        %% Horizontal spread band: mean fracture x +/- 1 SD
                        if stdFractureX > 0

                            xLeft = meanFractureX - stdFractureX;
                            xRight = meanFractureX + stdFractureX;

                            fill( ...
                                ax, ...
                                [xLeft xRight xRight xLeft], ...
                                [0 0 meanFractureY meanFractureY], ...
                                thisColor, ...
                                'FaceAlpha',0.12, ...
                                'EdgeColor','none', ...
                                'HandleVisibility','off');
                        end

                        %% Vertical drop line at the mean fracture point
                        plot( ...
                            ax, ...
                            [meanFractureX meanFractureX], ...
                            [meanFractureY 0], ...
                            'Color',thisColor, ...
                            'LineWidth',2.5, ...
                            'LineStyle','--', ...
                            'HandleVisibility','off');

                        %% Individual fracture points
                        scatter( ...
                            ax, ...
                            fractureX, ...
                            fractureY, ...
                            45, ...
                            thisColor, ...
                            'filled', ...
                            'MarkerEdgeColor','k', ...
                            'MarkerFaceAlpha',0.7, ...
                            'HandleVisibility','off');
                    end
                end
                %% ============================================================

                fprintf( ...
                    'Plotted %s average using %d curves.\n', ...
                    yearNumber, ...
                    size(interpolatedY,2));
            end

            %% Tick labels: bold, size 18
            set(ax,'FontSize',18,'FontWeight','bold');

            %% Axis labels: bold, size 20
            if strcmpi(testName,'Fracture')

                xlabel(ax,'Displacement (mm)', ...
                    'FontWeight','bold','FontSize',20);
                ylabel(ax,'Force (N)', ...
                    'FontWeight','bold','FontSize',20);

            else

                xlabel(ax,'Strain', ...
                    'FontWeight','bold','FontSize',20);
                ylabel(ax,'Stress (MPa)', ...
                    'FontWeight','bold','FontSize',20);

            end

            %% Title: "Material Test"  e.g. NEAT Compression
            title( ...
                ax, ...
                materialName + " " + testName, ...
                'Interpreter','none');

            if ~isempty(plotHandles)

                legend( ...
                    ax, ...
                    plotHandles, ...
                    cellstr(plottedYears), ...
                    'Location','best', ...
                    'Interpreter','tex', ...
                    'FontSize',11);

                axis(ax,'tight');

            else

                warning( ...
                    'No yearly averages were plotted for %s %s.', ...
                    materialName, testName);
            end

            %% Save graph (different name for the failure-line version)
            if addLineForThisTest
                saveName = ...
                    materialName + "_" + testName + ...
                    "_Yearly_Averages_WithFailureLine.png";
            else
                saveName = ...
                    materialName + "_" + testName + ...
                    "_Yearly_Averages.png";
            end

            savePath = fullfile(outputFolder,saveName);

            exportgraphics( ...
                fig, ...
                savePath, ...
                'Resolution',300);

            fprintf('Saved average plot: %s\n',savePath);
        end
    end
end


%% ========================================================================
%% Plot separate mean ± standard deviation graph for every year,
%% material, and test
%% ========================================================================

function plotYearTestStandardDeviationCurves( ...
    classifiedAll, organizedFolder, materials, tests, ...
    plotLimits, outputFolder)

    yearsToPlot = ["2023","2024","2025","2026"];

    numberOfAveragePoints = 500;

    for y = 1:length(yearsToPlot)

        yearNumber = yearsToPlot(y);
        yearFolderName = yearNumber + "_organized";

        for t = 1:length(tests)

            testName = string(tests{t});

            for m = 1:length(materials)

                materialName = string(materials{m});

                fprintf( ...
                    '\nMean and standard deviation: %s %s %s\n', ...
                    yearNumber, materialName, testName);

                %% Select files for one year, material, and test
                rows = ...
                    strcmpi( ...
                        strtrim(string(classifiedAll.Year)), ...
                        yearFolderName) & ...
                    strcmpi( ...
                        strtrim(string(classifiedAll.Test)), ...
                        testName) & ...
                    strcmpi( ...
                        strtrim(string(classifiedAll.Material)), ...
                        materialName);

                selected = classifiedAll(rows,:);

                if isempty(selected)

                    warning( ...
                        'No files found for %s %s %s.', ...
                        yearNumber, materialName, testName);

                    continue;
                end

                %% Read dimension file for compression and tension
                dims = table();

                if ~strcmpi(testName,'Fracture')

                    dimensionFile = fullfile( ...
                        organizedFolder, ...
                        yearFolderName, ...
                        "SpecimenDimensions" + ...
                        yearNumber + ".xlsx");

                    if ~isfile(dimensionFile)

                        warning( ...
                            'Dimension file not found: %s', ...
                            dimensionFile);

                        continue;
                    end

                    dims = readtable(dimensionFile);

                    if ~ismember( ...
                            'Material', ...
                            dims.Properties.VariableNames)

                        dims.Properties.VariableNames{2} = ...
                            'Material';
                    end
                end

                %% Process and store individual specimen curves
                xCurves = {};
                yCurves = {};

                for i = 1:height(selected)

                    csvPath = string(selected.FilePath(i));

                    if ~isfile(csvPath)

                        warning( ...
                            'CSV not found: %s', ...
                            csvPath);

                        continue;
                    end

                    groupName = string(selected.Group(i));

                    sectionNumber = str2double( ...
                        regexprep(groupName,'\D',''));

                    sampleName = string(selected.SampleName(i));

                    sampleNumber = str2double( ...
                        regexprep(sampleName,'\D',''));

                    [xCurve, yCurve, ok] = ...
                        processCurveForYearlyAverage( ...
                            csvPath, ...
                            dims, ...
                            sectionNumber, ...
                            sampleNumber, ...
                            testName, ...
                            materialName, ...
                            plotLimits);

                    if ~ok || ...
                            length(xCurve) < 2 || ...
                            length(yCurve) < 2
                        continue;
                    end

                    xCurves{end+1,1} = xCurve(:);
                    yCurves{end+1,1} = yCurve(:);
                end

                numberOfCurves = length(xCurves);

                if numberOfCurves == 0

                    warning( ...
                        'No valid curves for %s %s %s.', ...
                        yearNumber, materialName, testName);

                    continue;
                end

                %% Determine interpolation domain
                curveStarts = cellfun( ...
                    @(x) min(x), xCurves);

                curveEnds = cellfun( ...
                    @(x) max(x), xCurves);

                if strcmpi(testName,'Compression')

                    % Keep the full compression response.
                    commonStart = 0;

                    commonEnd = min( ...
                        max(curveEnds), ...
                        plotLimits.compression);

                else

                    % Tension and fracture use a range shared by
                    % all valid specimens.
                    commonStart = max(curveStarts);
                    commonEnd = min(curveEnds);
                end

                if ~isfinite(commonStart) || ...
                        ~isfinite(commonEnd) || ...
                        commonEnd <= commonStart

                    warning( ...
                        ['Invalid interpolation range for ' ...
                         '%s %s %s.'], ...
                        yearNumber, materialName, testName);

                    continue;
                end

                commonX = linspace( ...
                    commonStart, ...
                    commonEnd, ...
                    numberOfAveragePoints)';

                interpolatedY = NaN( ...
                    numberOfAveragePoints, ...
                    numberOfCurves);

                %% Interpolate specimens onto the common x-axis
                for c = 1:numberOfCurves

                    xCurrent = xCurves{c};
                    yCurrent = yCurves{c};

                    validCurrent = ...
                        isfinite(xCurrent) & ...
                        isfinite(yCurrent);

                    xCurrent = xCurrent(validCurrent);
                    yCurrent = yCurrent(validCurrent);

                    [xCurrent, sortIndex] = sort(xCurrent);
                    yCurrent = yCurrent(sortIndex);

                    [xCurrent, uniqueIndex] = ...
                        unique(xCurrent,'stable');

                    yCurrent = yCurrent(uniqueIndex);

                    if length(xCurrent) < 2
                        continue;
                    end

                    interpolatedY(:,c) = interp1( ...
                        xCurrent, ...
                        yCurrent, ...
                        commonX, ...
                        'linear', ...
                        NaN);
                end

                %% Remove curves whose interpolation completely failed
                validColumns = ...
                    sum(isfinite(interpolatedY),1) >= 2;

                interpolatedY = ...
                    interpolatedY(:,validColumns);

                numberIncluded = size(interpolatedY,2);

                if numberIncluded == 0

                    warning( ...
                        ['Interpolation failed for every curve: ' ...
                         '%s %s %s.'], ...
                        yearNumber, materialName, testName);

                    continue;
                end

                %% Number of curves contributing at each x-location
                contributingCount = ...
                    sum(isfinite(interpolatedY),2);

                %% Point-by-point average and standard deviation
                averageY = mean( ...
                    interpolatedY, ...
                    2, ...
                    'omitnan');

                standardDeviationY = std( ...
                    interpolatedY, ...
                    0, ...
                    2, ...
                    'omitnan');

                %% Standard deviation is undefined with only one curve
                standardDeviationY( ...
                    contributingCount < 2) = NaN;

                %% Remove points with no valid average
                validAverage = ...
                    isfinite(commonX) & ...
                    isfinite(averageY);

                commonX = commonX(validAverage);
                averageY = averageY(validAverage);
                standardDeviationY = ...
                    standardDeviationY(validAverage);

                contributingCount = ...
                    contributingCount(validAverage);

                if isempty(commonX)
                    continue;
                end

                %% Cut final fracture average at its maximum
                if strcmpi(testName,'Fracture')

                    [~, averagePeakIndex] = max(averageY);

                    commonX = commonX(1:averagePeakIndex);
                    averageY = averageY(1:averagePeakIndex);

                    standardDeviationY = ...
                        standardDeviationY(1:averagePeakIndex);

                    contributingCount = ...
                        contributingCount(1:averagePeakIndex);
                end

                %% Upper and lower standard-deviation boundaries
                lowerBound = ...
                    averageY - standardDeviationY;

                upperBound = ...
                    averageY + standardDeviationY;

                % Force and stress should not be below zero
                lowerBound(lowerBound < 0) = 0;

                %% Only shade points where standard deviation exists
                shadeValid = ...
                    isfinite(commonX) & ...
                    isfinite(lowerBound) & ...
                    isfinite(upperBound);

                xShade = commonX(shadeValid);
                lowerShade = lowerBound(shadeValid);
                upperShade = upperBound(shadeValid);

                %% Create figure
                fig = figure( ...
                    'Visible','on', ...
                    'Units','normalized', ...
                    'Position',[0.12 0.10 0.72 0.76]);

                ax = axes(fig);

                hold(ax,'on');
                grid(ax,'on');
                box(ax,'on');

                %% Draw shaded standard-deviation region
                if length(xShade) >= 2

                    shadeHandle = fill( ...
                        ax, ...
                        [xShade; flipud(xShade)], ...
                        [lowerShade; flipud(upperShade)], ...
                        [0.5 0.5 0.5], ...
                        'FaceAlpha',0.25, ...
                        'EdgeColor','none', ...
                        'DisplayName','Mean \pm 1 standard deviation');

                else

                    shadeHandle = gobjects(0);
                end

                %% Draw average curve over the shaded region
                meanHandle = plot( ...
                    ax, ...
                    commonX, ...
                    averageY, ...
                    'LineWidth',2.5, ...
                    'DisplayName', ...
                    sprintf( ...
                        'Average curve (n = %d)', ...
                        numberIncluded));

                %% Labels
                if strcmpi(testName,'Fracture')

                    xlabel(ax,'Displacement (mm)');
                    ylabel(ax,'Force (N)');

                else

                    xlabel(ax,'Strain');
                    ylabel(ax,'Stress (MPa)');
                end

                title( ...
                    ax, ...
                    apEpoxyLabel(yearNumber) + " " + ...    % <<< CHANGED
                    materialName + " " + ...
                    testName + ...
                    " — Mean \pm Standard Deviation");

                if isempty(shadeHandle)

                    legend( ...
                        ax, ...
                        meanHandle, ...
                        'Location','best', ...
                        'Interpreter','tex');

                else

                    legend( ...
                        ax, ...
                        [meanHandle, shadeHandle], ...
                        'Location','best', ...
                        'Interpreter','tex');
                end

                axis(ax,'tight');

                %% Add minimum contributor information
                positiveCounts = ...
                    contributingCount(contributingCount > 0);

                if ~isempty(positiveCounts)

                    minimumContributors = min(positiveCounts);

                    subtitle( ...
                        ax, ...
                        sprintf( ...
                            ['Curves included: %d; minimum curves ' ...
                             'contributing at any plotted point: %d'], ...
                            numberIncluded, ...
                            minimumContributors));
                end

                %% Save graph (file name still uses the year so files
                %% stay sortable and don't contain "%" or "/")
                saveName = ...
                    yearNumber + "_" + ...
                    materialName + "_" + ...
                    testName + ...
                    "_Mean_StdDev.png";

                savePath = fullfile( ...
                    outputFolder, ...
                    saveName);

                exportgraphics( ...
                    fig, ...
                    savePath, ...
                    'Resolution',300);

                fprintf( ...
                    ['Saved mean and standard-deviation plot ' ...
                     'using %d curves:\n%s\n'], ...
                    numberIncluded, ...
                    savePath);
            end
        end
    end
end


%% ========================================================================
%% Plot Young's modulus values by AP/Epoxy ratio (one x position per year)
%% ========================================================================

function plotYoungsModulusResults( ...

    individualResults, yearlySummary, ...
    years, materials, tests, outputFolder)

    xPositions = 1:length(years);

    %% AP/Epoxy tick labels, one per year                  % <<< CHANGED
    ratioLabels = strings(1,length(years));
    for k = 1:length(years)
        ratioLabels(k) = apEpoxyLabel(years(k));
    end

    for m = 1:length(materials)

        materialName = materials(m);

        for t = 1:length(tests)

            testName = tests(t);

            fig = figure( ...
                'Visible','on', ...
                'Units','normalized', ...
                'Position',[0.18 0.12 0.65 0.72]);

            ax = axes(fig);

            hold(ax,'on');
            grid(ax,'on');
            box(ax,'on');

            meanValues = NaN(length(years),1);
            stdValues = NaN(length(years),1);

            specimenHandle = gobjects(0);

            for y = 1:length(years)

                yearNumber = years(y);

                %% Individual specimen moduli
                specimenRows = ...
                    strcmpi(individualResults.Year,yearNumber) & ...
                    strcmpi(individualResults.Material,materialName) & ...
                    strcmpi(individualResults.Test,testName);

                specimenValues = ...
                    individualResults.YoungsModulus_MPa( ...
                        specimenRows);

                specimenValues = ...
                    specimenValues(isfinite(specimenValues));

                if ~isempty(specimenValues)

                    if length(specimenValues) == 1

                        offsets = 0;

                    else

                        offsets = linspace( ...
                            -0.10, ...
                            0.10, ...
                            length(specimenValues))';
                    end

                    h = scatter( ...
                        ax, ...
                        xPositions(y) + offsets, ...
                        specimenValues, ...
                        38, ...
                        'filled', ...
                        'MarkerFaceAlpha',0.45, ...
                        'DisplayName','Individual specimens');

                    if isempty(specimenHandle)

                        specimenHandle = h;

                    else

                        h.HandleVisibility = 'off';
                    end
                end

                %% Yearly mean and standard deviation
                summaryRows = ...
                    strcmpi(yearlySummary.Year,yearNumber) & ...
                    strcmpi(yearlySummary.Material,materialName) & ...
                    strcmpi(yearlySummary.Test,testName);

                if any(summaryRows)

                    meanValues(y) = ...
                        yearlySummary.MeanYoungsModulus_MPa( ...
                            summaryRows);

                    stdValues(y) = ...
                        yearlySummary.StandardDeviation_MPa( ...
                            summaryRows);
                end
            end

            validSummary = isfinite(meanValues);

            if any(validSummary)

                meanHandle = errorbar( ...
                    ax, ...
                    xPositions(validSummary), ...
                    meanValues(validSummary), ...
                    stdValues(validSummary), ...
                    'o-', ...
                    'LineWidth',2.2, ...
                    'MarkerSize',8, ...
                    'MarkerFaceColor','auto', ...
                    'CapSize',12, ...
                    'DisplayName','Mean \pm 1 SD');

                if isempty(specimenHandle)

                    legend( ...
                        ax, ...
                        meanHandle, ...
                        'Location','best', ...
                        'Interpreter','tex');

                else

                    legend( ...
                        ax, ...
                        [specimenHandle,meanHandle], ...
                        'Location','best', ...
                        'Interpreter','tex');
                end
            end

            xticks(ax,xPositions);
            xticklabels(ax,cellstr(ratioLabels));          % <<< CHANGED

            xlim(ax,[0.5,length(years) + 0.5]);

            xlabel(ax,'AP / Epoxy Ratio');                 % <<< CHANGED
            ylabel(ax,'Young''s Modulus (MPa)');

            title( ...
                ax, ...
                materialName + " " + testName + ...
                " Young's Modulus", ...
                'Interpreter','none');

            saveName = ...
                materialName + "_" + ...
                testName + ...
                "_Youngs_Modulus.png";

            exportgraphics( ...
                fig, ...
                fullfile(outputFolder,saveName), ...
                'Resolution',300);
        end
    end
end



